### ISSUE TITLE
supportedUCSCtables misses some tables

### ISSUE THREAD

**Issue by jmacdon** [Bioconductor/txdbmaker#7]
After running `UCSC.utils:::list_UCSC_tracks`, the output is filtered on the 'type' column, keeping only genePred table types. But this ignores knownGene (which is what we use for most of the `TxDb` packages:

```
        track primary_table                                   type group composite_track
9 GENCODE V46     knownGene bigGenePred knownGenePep knownGeneMrna genes            <NA>
```

Should 'bigGenePred' be included in the filtering criteria?

**Comment by hpages** [comment]
oops, missed this! Fixed now (see commit 05d278f13d8cbe3ab29a46ae039e7689615ebe65). Thanks @jmacdon
