### ISSUE TITLE
Could not load package txdbmaker

### ISSUE THREAD

**Issue by Scoupshan** [Bioconductor/txdbmaker#9]
hello everone,
I met an error below when I run this: 
txdb <- makeTxDbFromGFF("C:/Users/Administrator/Documents/ref/genes_longest.gtf",
+                         format = "gtf" )

load_package_gracefully("txdbmaker", "starting with BioC 3.19, ", : 
  Could not load package txdbmaker. Is it installed?

  Note that starting with BioC 3.19, calling makeTxDbFromGFF() requires the txdbmaker package.
  Please install it with:

    BiocManager::install("txdbmaker")

But I have already installed all the packages.
Can anyone help ?

**Comment by hpages** [comment]
Please show us the output of:
```
library(txdbmaker)

sessionInfo()
```
Thanks!

**Comment by ICE0584** [comment]
i am not able to install it because 

package ‘txdbmaker’ is not available for Bioconductor version '3.18'

what can i do?

**Comment by hpages** [comment]
@ICE0584 

**txdbmaker** was introduced in Bioconductor 3.19 so you need to upgrade your installation. We strongly recommend that you install the latest version of Bioconductor: 3.20 (requires R 4.4).

Besides Bioconductor 3.18 is old and is no longer maintained/supported.

If for whatever reason you're stuck with Bioconductor 3.18, then you don't need **txdbmaker**. Before the introduction of the package in Bioconductor 3.19, all the functionality that is now found in **txdbmaker** was in the **GenomicFeatures** package. So any function from **txdbmaker** that you are looking for should be in **GenomicFeatures**. Unless you are mixing packages from different versions of Bioconductor which would be a terrible idea but that's another story (note that this kind of version mismatch should never happen if you always install package with `BiocManager::install()`).

**Comment by hpages** [comment]
@Scoupshan No news == good news I guess so I'm closing this
